### ISSUE TITLE
Automatically re-run failed behat CI jobs an extra one or two times

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#190]
Behat sporadically fails a lot in CI causing entire builds to go red.  The normal solution is to just re-run a job a one or two times and watch it pass.  It's pretty annoying and makes our builds look far worse than they actually are.

To save this annoyance, we should automatically re-run behat jobs that fail one or two times.

This should only happen in a automatically triggered CI context and not in a PR/Push context because some of the longer jobs take 30 minutes, and we don't want 1.5 hour CI runs for legit behat failures on pull-requests

One exception will be for push will auto-merge-ups where we would want them to auto re-run, so probably will need a input value to specify running multiple times

## Notes

The `@retry` annotation in feature files may do this, not sure

**Comment by GuySartorelli** [comment]
I'm trying `@retry` on a behat feature that commonly fails in admin - see https://github.com/silverstripe/silverstripe-admin/pull/1679
If that does noticably reduce the number of admin failures, it might be worth applying a sort of global `@retry` tag, since it retries only the specific step for a set amount of time, so interruption even on PRs will be fairly minimal for legitimate failures.

**Comment by GuySartorelli** [comment]
This was done another way already
