### ISSUE TITLE
Failed auto-merge-ups

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#216]
Rhino is reporting a few failed merge-ups: https://rhino.silverstripe.org/?t=merge-ups

**Comment by emteknetnz** [comment]
Have resolved
- silverstripe-auditor
- silverstripe-segment-field
- silverstripe-sharedraftcontent
- developer-docs

Have re-run a bunch of merge-up workflows where there were pending changes from CMS 5 to CMS 6, lots more will break because of all the updated yarn.lock files from merging the Update JS PRs.

Re-run rhino to see what's red
